version: "3"
services:
    dexbot:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: dexbot
        restart: unless-stopped
        env_file:
            - .env
